
### sign up 
POST http://localhost:3003/api/auth/signup
Content-Type: application/json

{
    "name": "py",
    "account": "pyfissh@gmail.com",
    "password": "py12345678",
    "confirm_password": "py12345678",
    "hint": "already"
}

### verify sign up
GET http://localhost:3003/api/auth/signup/eyJlbWFpbCI6ImxpekBnbWFpbC5jb20ifQ==
Content-Type: application/json

### auth
### -> paste access_token behind the 'Bearer' with space.
### -> response 200 or 401/403
GET http://localhost:3003/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmlzaGJveTE5MCIsImVtYWlsIjoiZmlzaGJveTE5MEBnbWFpbC5jb20iLCJpYXQiOjE2NTQxODM5OTksImV4cCI6MTY1NDE4NDAxOX0.4Hb9Om9MZFl1V0NpBEZ3SL6clPBR5R3owghrchSjSp8

### token
### -> paste refresh_token behind the 'token' with quotes.
### -> response 'access_token' or 401/403
POST http://localhost:3003/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmlzaGJveTE5MCIsImVtYWlsIjoiZmlzaGJveTE5MEBnbWFpbC5jb20iLCJpYXQiOjE2NTQxODMwMjl9.xzmeV1sbN42fyfUufizXxFQDIoF0YtSW2XnYQ1hAYtw"
}

### signin
### -> paste 'account' and 'password' which already existed in database
### -> response 'access_token' and 'refresh_token'
POST http://localhost:3003/api/auth/signin
Content-Type: application/json

{
    "account": "pyfissh@gmail.com",
    "password": "py12345678"
}

### signout
### -> paste 'refresh_token' behind the 'token'
### -> response 204 or 401/403
DELETE http://localhost:3003/api/auth/signout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHkiLCJlbWFpbCI6InB5Zmlzc2hAZ21haWwuY29tIiwiaWF0IjoxNjU0NDUzMzcxfQ.EZuaR_iNPh_2odZrYpr7SkkyuTQfLqo8k9I4dX-OJCc"
}
